package main

var sites = []string{
	"https://www.avito.ru/",
	"https://www.ozon.ru/",
	"https://vk.com/",
	"https://yandex.ru/",
	"https://www.google.com/",
	"https://www.youtube.com/",
	"https://www.facebook.com/",
	"https://www.wikipedia.org/",
	"https://www.amazon.com/",
	"https://www.twitter.com/",
	"https://www.instagram.com/",
	"https://www.linkedin.com/",
	"https://www.stepik.org/",
	"https://www.pinterest.com/",
	"https://www.netflix.com/",
	"https://www.reddit.com/",
	"https://www.ebay.com/",
	"https://www.bing.com/",
	"https://www.microsoft.com/",
	"https://www.tumblr.com/",
	"https://www.imdb.com/",
	"https://www.habr.com/",
	"https://www.banki.ru/",
	"https://www.spotify.com/",
	"https://www.yelp.com/",
	"https://www.rottentomatoes.com/",
	"https://www.walmart.com/",
	"https://www.apple.com/",
	"https://www.bestbuy.com/",
	"https://www.espn.com/",
	"https://www.redis.com/",
	"https://www.ted.com/",
	"https://www.nytimes.com/",
	"https://www.hh.ru/",
}
